# Generated by Django 2.1.1 on 2018-09-27 20:28

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('quiz', '0001_initial'),
    ]

    operations = [
        migrations.AlterField(
            model_name='question',
            name='image',
            field=models.URLField(default='https://res.cloudinary.com/dz2bsme0a/image/upload/v1538070889/ques.png'),
        ),
    ]
