# Generated by Django 2.0.2 on 2018-09-20 18:41

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('quiz', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='quiz',
            name='testpass',
            field=models.CharField(default=' ', max_length=50),
        ),
    ]
