# Generated by Django 2.1.1 on 2018-09-22 09:13

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('quiz', '0001_initial'),
    ]

    operations = [
        migrations.AlterField(
            model_name='quiz',
            name='Quiz_id',
            field=models.CharField(default='', max_length=50),
        ),
        migrations.AlterField(
            model_name='quiz',
            name='Test_Password',
            field=models.CharField(default='', max_length=50),
        ),
    ]
