# Generated by Django 2.0.2 on 2018-09-20 19:04

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('quiz', '0002_quiz_testpass'),
    ]

    operations = [
        migrations.RenameField(
            model_name='quiz',
            old_name='testpass',
            new_name='Quiz_id',
        ),
        migrations.AddField(
            model_name='quiz',
            name='Test_Password',
            field=models.CharField(default=' ', max_length=50),
        ),
    ]
