# Generated by Django 2.1.1 on 2018-09-20 20:31

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('quiz', '0003_question'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='quiz',
            name='questions',
        ),
        migrations.AddField(
            model_name='quiz',
            name='q_id',
            field=models.CharField(default='', max_length=50),
            preserve_default=False,
        ),
        migrations.AddField(
            model_name='quiz',
            name='q_password',
            field=models.CharField(default='Enter Quiz Id', max_length=50),
            preserve_default=False,
        ),
    ]
