# Generated by Django 2.1.1 on 2018-09-21 21:52

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('quiz', '0003_auto_20180921_0034'),
    ]

    operations = [
        migrations.RenameField(
            model_name='quiz',
            old_name='questions',
            new_name='instructions',
        ),
    ]
