# Generated by Django 2.1.1 on 2018-09-20 20:33

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('quiz', '0004_auto_20180921_0201'),
    ]

    operations = [
        migrations.RenameField(
            model_name='quiz',
            old_name='q_id',
            new_name='quiz_id',
        ),
        migrations.RenameField(
            model_name='quiz',
            old_name='q_password',
            new_name='quiz_password',
        ),
    ]
