# Generated by Django 2.0.2 on 2018-09-28 11:28

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('quiz', '0005_score'),
    ]

    operations = [
        migrations.AddField(
            model_name='answers',
            name='users_appeared',
            field=models.TextField(default='', max_length=200),
        ),
    ]
