# Generated by Django 2.1.1 on 2018-09-21 20:34

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('quiz', '0005_auto_20180921_0203'),
    ]

    operations = [
        migrations.AlterField(
            model_name='quiz',
            name='quiz_password',
            field=models.CharField(default=' ', max_length=50),
        ),
    ]
