# Generated by Django 2.1.1 on 2018-09-21 22:08

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('quiz', '0006_auto_20180922_0204'),
    ]

    operations = [
        migrations.AlterField(
            model_name='quiz',
            name='quiz_password',
            field=models.CharField(max_length=50),
        ),
    ]
