# Generated by Django 2.0.2 on 2018-10-15 03:40

import django.core.validators
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('quiz', '0009_auto_20181015_0845'),
    ]

    operations = [
        migrations.AlterField(
            model_name='quiz',
            name='negative',
            field=models.IntegerField(default=1, validators=[django.core.validators.MaxValueValidator(100), django.core.validators.MinValueValidator(1)]),
        ),
    ]
