# Generated by Django 2.0.2 on 2018-10-15 03:56

import django.core.validators
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('quiz', '0010_auto_20181015_0910'),
    ]

    operations = [
        migrations.AlterField(
            model_name='quiz',
            name='negative',
            field=models.PositiveIntegerField(default=0, validators=[django.core.validators.MaxValueValidator(100), django.core.validators.MinValueValidator(1)]),
        ),
        migrations.AlterField(
            model_name='quiz',
            name='positive',
            field=models.PositiveIntegerField(default=3),
        ),
    ]
