# Generated by Django 2.0.2 on 2018-10-15 03:56

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('quiz', '0011_auto_20181015_0926'),
    ]

    operations = [
        migrations.AlterField(
            model_name='quiz',
            name='negative',
            field=models.PositiveIntegerField(default=0),
        ),
    ]
